name: Nextraction Backend - Deploy Only

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ec2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker --version

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: |
          docker pull bitaouioussama/nextraction:v2

      - name: Deploy container
        run: |
          docker stop nextraction-app || true
          docker rm nextraction-app || true

          docker run -d \
            --name nextraction-app \
            --restart unless-stopped \
            -e PORT=8000 \
            -p 8000:8000 \
            --env-file /home/ubuntu/nextraction.env \
            bitaouioussama/nextraction:v2
