name: Nextraction Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker --version

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nextraction:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nextraction:latest

      - name: Deploy container
        run: |
          docker stop python-backend || true
          docker rm python-backend || true

          docker run -d \
            --name nextraction \
            -p 8000:8000 \
            ${{ secrets.DOCKER_USERNAME }}/nextraction:latest
